import { d as derived, w as writable } from "./index.js";
const portfolioPageTitle$1 = "Our Portfolio";
const portfolio$1 = { "pageTitle": "Our Work", "meta": { "client": "Client", "category": "Category", "year": "Year", "status": "Status", "title": "Portfolio — Nomadic Digital", "description": "Explore selected projects and digital products crafted by Nomadic Digital." }, "sections": { "scope": "Scope", "deliverables": "Deliverables", "technology": "Technology" }, "cta": { "startSimilar": "Start a similar project" }, "status": { "live": "Live", "inProgress": "In progress", "completed": "Completed" }, "categories": { "ecommerceBrandPlatform": "E-commerce · Brand platform", "saasDigitalAdvertising": "SaaS · Digital advertising", "corporateWebsite": "Corporate website", "saasSportsManagement": "SaaS · Sports management", "ecommerceBrandWebsite": "E-commerce · Brand website", "corporateBrandWebsite": "Corporate · Brand website" }, "scope": { "platformArchitecture": "Platform architecture", "uxUiDesign": "UX / UI design", "ecommerceDevelopment": "E-commerce development", "erpApiIntegrations": "ERP & API integrations", "performanceOptimization": "Performance optimization", "saasArchitecture": "SaaS architecture", "adminDashboard": "Admin dashboard", "tabletInterface": "Tablet interface", "reportingAnalytics": "Reporting & analytics", "roleBasedAccess": "Role-based access", "websiteDevelopment": "Website development", "seoStructure": "SEO structure", "memberManagement": "Member management", "paymentFlows": "Payment flows", "mobileFirstUx": "Mobile-first UX", "brandUx": "Brand UX", "productPresentation": "Product presentation", "seoOptimization": "SEO optimization", "websiteRedesign": "Website redesign", "contentStructure": "Content structure", "brandPresentation": "Brand presentation", "automation": "Process automation" }, "deliverables": { "customStorefront": "Custom storefront", "adminDashboard": "Admin dashboard", "productStockSync": "Product & stock sync", "seoReadyStructure": "SEO-ready structure", "analyticsSetup": "Analytics setup", "webAdminPlatform": "Web admin platform", "tabletUi": "Tablet UI", "campaignReporting": "Campaign reporting", "clientDashboards": "Client dashboards", "corporateWebsite": "Corporate website", "responsiveLayouts": "Responsive layouts", "seoReadyPages": "SEO-ready pages", "webAdminPanel": "Web admin panel", "memberDashboard": "Member dashboard", "paymentSystem": "Payment system", "classScheduling": "Class scheduling", "productPages": "Product pages", "contentDrivenLayout": "Content-driven layout", "multilingualStructure": "Multilingual structure", "automatedInvoicing": "Automated invoicing", "mobileDevelopment": "Mobile development" }, "metrics": { "pageSpeed": "Page speed", "conversionRate": "Conversion rate", "bounceRate": "Bounce rate", "activeScreens": "Active screens", "monthlyImpressions": "Monthly impressions", "clubsOnboarded": "Clubs onboarded", "activeMembers": "Active members" }, "roles": { "ecommerceOperations": "E-commerce & Operations" }, "projects": { "conte": { "demos": { "stock": { "title": "Real-time stock synchronization", "body": "Automatic stock updates between the e-commerce platform and the ERP system, ensuring accurate availability across all channels without manual intervention." }, "dashboard": { "title": "High-conversion commerce experience", "body": "A conversion-focused storefront and admin experience optimized to reduce friction, guide purchase decisions, and improve overall checkout performance." }, "uiux": { "title": "UX & UI optimization", "body": "Interface optimizations focused on clarity, usability, and conversion across all devices while preserving a premium brand feel." }, "platform": { "title": "E-commerce platform architecture", "body": "A scalable platform supporting both B2C and B2B flows, built for performance, reliability, and long-term growth." } }, "overview": { "headline": "A Shopify-based e-commerce ecosystem optimized for scale.", "description": "Conte needed a robust Shopify setup tightly integrated with their ERP and B2B operations, while supporting ongoing growth, automation, and brand repositioning." }, "outcomes": { "headline": "Operational clarity, automation, and scalable growth.", "description": "Manual work was reduced through ERP and B2B integrations, internal tools streamlined daily operations, and the rebrand was executed consistently across digital channels." }, "testimonial": { "quote": "The integrations and automation fundamentally changed how we operate day-to-day, giving us stability and room to scale." } }, "locallia": { "demos": { "dashboard": { "title": "Campaign & device dashboard", "body": "A real-time dashboard for managing campaigns, devices, and impressions across the advertising network." }, "analytics": { "title": "Reporting & analytics", "body": "Transparent reporting that turns physical ad exposure into measurable, data-driven insights." }, "platform": { "title": "SaaS platform architecture", "body": "A scalable SaaS foundation supporting multi-tenant usage, device management, and future expansion." } }, "overview": { "headline": "A location-based advertising platform for real-world impact.", "description": "Locallia connects brands with local audiences through smart, data-driven in-car advertising and transparent performance reporting." }, "outcomes": { "headline": "Turning physical reach into measurable performance.", "description": "A robust SaaS foundation enabling real-time reporting, scalable device management, and clear performance insights." } }, "kronburg": { "demos": { "uiux": { "title": "Corporate UX & UI design", "body": "A restrained, professional interface designed to communicate trust, structure, and clarity." }, "website": { "title": "Corporate website development", "body": "A fast, SEO-optimized website focused on clear communication and long-term maintainability." } }, "overview": { "headline": "A clean corporate presence built on clarity and trust.", "description": "Kronburg required a restrained, professional website that communicated reliability and structure without visual noise." }, "outcomes": { "headline": "A digital presence built on trust and restraint.", "description": "A clear brand message delivered with fast load times, SEO clarity, and minimal distraction." } }, "fluxum": { "demos": { "dashboard": { "title": "Club & admin dashboard", "body": "A centralized dashboard for managing members, classes, payments, and communication across clubs." }, "payments": { "title": "Payments & subscriptions", "body": "Integrated recurring payments and subscription management tailored for sports organizations." }, "platform": { "title": "SaaS system architecture", "body": "A scalable platform designed to support multiple clubs, roles, and future feature expansion." } }, "overview": { "headline": "A modern platform for managing sports clubs and communities.", "description": "Fluxum simplifies memberships, payments, scheduling, and communication for gyms and sports clubs." }, "outcomes": { "headline": "Simplifying complex club operations into one platform.", "description": "Club operations are centralized into a single system, reducing administrative overhead and improving daily workflows." } }, "natscent": { "demos": { "uiux": { "title": "Editorial UX & visual identity", "body": "A calm, editorial interface designed to support storytelling while guiding users toward conversion." }, "ecommerce": { "title": "E-commerce storefront", "body": "A streamlined shopping experience optimized for product discovery and smooth checkout." } }, "overview": { "headline": "A refined e-commerce experience for a fragrance brand.", "description": "Natscent required a calm, editorial-style storefront that balanced storytelling with conversion." }, "outcomes": { "headline": "An editorial storefront designed to convert.", "description": "The experience balances brand narrative and commerce while maintaining a smooth purchase flow." } }, "viorica": { "demos": { "erpSync": { "title": "ERP product & stock synchronization", "body": "Automated synchronization between the online store and the ERP system, ensuring product data, stock levels, and pricing remain consistent across systems." }, "orderAutomation": { "title": "Order processing automation", "body": "Orders placed online are automatically pushed into the ERP, reducing manual processing, operational delays, and human error." } }, "overview": { "headline": "ERP integration and operational automation for a cosmetics brand.", "description": "Viorica required a reliable integration layer between their e-commerce platform and ERP system to streamline operations and maintain data accuracy at scale." }, "outcomes": { "headline": "Reduced manual work through reliable ERP automation.", "description": "The integration enabled automated product sync and order processing, improving operational efficiency and reducing the risk of inconsistencies across systems." } } } };
const blog$1 = { "pageTitle": "Blog", "index": { "title": "Our News", "subtitle": "Stories, updates, and inspirations to you." }, "roles": { "productStrategist": "Product Strategist", "uiuxDesigner": "UI/UX Designer", "securityLead": "Security Lead", "cfoCoFounder": "CFO & Co-founder", "growthAnalyst": "Growth Analyst" }, "posts": { "metricsForSaas": { "title": "5 Metrics Every SaaS Founder Should Track", "description": "Learn which KPIs matter when scaling your SaaS.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Understanding the Numbers</h2><p class="font-[550]">Knowing what to measure is essential when you’re growing a product. Metrics like churn, lifetime value, and customer acquisition cost offer powerful insights into the health of your business. Without these numbers, decisions are just guesses.</p></div><div><h2 class="text-2xl font-semibold mb-3">The Metrics That Matter</h2><p class="font-[550]">While there are many metrics to choose from, not all carry equal weight. Prioritize user engagement, conversion rates, and feature usage to truly understand how your product delivers value. These indicators guide you toward meaningful action.</p></div><div><h2 class="text-2xl font-semibold mb-3">Applying the Insights</h2><p class="font-[550]">Tracking metrics is only half the equation—what you do with them matters more. Use your data to validate ideas, improve user experiences, and spot areas of opportunity. Regular reviews lead to smarter decisions and more focused growth.</p></div></div>' }, "simplerDashboard": { "title": "How We Designed a Simpler Dashboard Experience", "description": "A behind-the-scenes look at how we built a dashboard that’s clear, fast, and user-focused.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Design Challenges</h2><p class="font-[550]">We began by identifying the most confusing elements in our current dashboard...</p></div><div><h2 class="text-2xl font-semibold mb-3">Simplifying the UI</h2><p class="font-[550]">Through testing and feedback, we refined the layout to improve clarity and reduce clutter...</p></div></div>' }, "secureSyncing": { "title": "Why Secure Syncing Matters More Than Ever", "description": "Explore how our security-first approach keeps your financial data safe and your mind at ease.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Risks of Insecure Data</h2><p class="font-[550]">Data syncing can expose vulnerabilities if not done correctly...</p></div><div><h2 class="text-2xl font-semibold mb-3">How We Secure It</h2><p class="font-[550]">We use end-to-end encryption and strict access controls to ensure only authorized users can access sensitive data...</p></div></div>' }, "scalingFinance": { "title": "Scaling Your Startup Finance Without Stress", "description": "Discover practical strategies and tools to manage your finances as your startup grows.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Establishing Financial Hygiene</h2><p class="font-[550]">Even in early-stage startups, basic financial hygiene is critical...</p></div><div><h2 class="text-2xl font-semibold mb-3">Tools for Scaling</h2><p class="font-[550]">We recommend automated forecasting tools and clear cash flow tracking dashboards...</p></div></div>' }, "lessons10k": { "title": "What We Learned From 10K+ Users", "description": "Insights and lessons from real users that are shaping the future of our product.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">User Behavior Insights</h2><p class="font-[550]">From onboarding to long-term usage, we tracked trends that revealed unexpected needs...</p></div><div><h2 class="text-2xl font-semibold mb-3">Adapting Our Product</h2><p class="font-[550]">We made several changes in response to these findings, including simplifying signup and improving support visibility...</p></div></div>' } } };
const privacy$1 = { "meta": { "title": "Privacy Policy — Nomadic Digital", "description": "Learn how Nomadic Digital collects, uses, and protects your personal data in compliance with GDPR." }, "title": "Privacy Policy", "lastUpdated": "Last updated: {date}", "intro": "<b>Nomadic Digital</b> (“we”, “our”, or “us”) values your privacy. This Privacy Policy explains how we collect, use, and protect your information when you visit our website or contact us through our forms.", "sections": { "collect": { "title": "1. Information we collect", "text": "We may collect personal information that you voluntarily provide to us, including:", "items": { "name": "Name", "email": "Email address", "message": "Message content", "optional": "Any information you choose to include when contacting us" } }, "usage": { "title": "2. How we use your information", "text": "We use the information we collect solely to:", "items": { "reply": "Respond to inquiries and messages", "projects": "Communicate about potential projects or services", "improve": "Improve our website and services" }, "note": "We do not sell, rent, or trade your personal data." }, "security": { "title": "3. Data storage & security", "text": "We take reasonable technical and organizational measures to protect your data. Messages sent through our contact form are transmitted securely and accessed only by authorized personnel." }, "cookies": { "title": "4. Cookies & analytics", "text": "Our website may use basic analytics tools to understand website traffic and usage. These tools collect anonymous, aggregated data and do not personally identify you." }, "rights": { "title": "5. Your rights (GDPR)", "text": "If you are located in the European Union, you have the right to:", "items": { "access": "Request access to your personal data", "modify": "Request correction or deletion of your data", "withdraw": "Withdraw consent at any time" } }, "contact": { "title": "6. Contact", "text": "If you have any questions about this Privacy Policy or how we handle your data, you can contact us at:" } } };
const terms$1 = { "meta": { "title": "Terms & Conditions — Nomadic Digital", "description": "Read the terms and conditions governing the use of Nomadic Digital’s website and services." }, "title": "Terms & Conditions", "lastUpdated": "Last updated: {date}", "intro": "These Terms & Conditions govern your use of the Nomadic Digital website and services. By accessing this site or contacting us, you agree to these terms.", "sections": { "about": { "title": "1. About us", "text": "Nomadic Digital provides digital services including web design, development, branding, SEO, and marketing strategy. All information on this site is provided for general informational purposes." }, "usage": { "title": "2. Use of the website", "text": "You agree to use this website only for lawful purposes. You must not:", "items": { "access": "Attempt to gain unauthorized access to the website or systems", "damage": "Use the website in a way that could damage or impair functionality", "copy": "Copy or reuse content without permission" } }, "services": { "title": "3. Services & proposals", "text": "Any services offered are subject to a separate agreement, proposal, or contract. Submitting a contact form or inquiry does not create a binding agreement." }, "ip": { "title": "4. Intellectual property", "text": "All content on this website—including text, visuals, branding, and layout—is the property of Nomadic Digital unless otherwise stated. You may not reproduce or distribute any content without written permission." }, "liability": { "title": "5. Limitation of liability", "text": "We make reasonable efforts to ensure the accuracy of information on this site, but we do not guarantee that all content is complete or up to date. We are not liable for any damages resulting from the use or inability to use this website." }, "links": { "title": "6. External links", "text": "This website may contain links to third-party websites. We are not responsible for the content or practices of those sites." }, "changes": { "title": "7. Changes to these terms", "text": "We may update these Terms & Conditions from time to time. Any changes will be posted on this page with an updated revision date." }, "contact": { "title": "8. Contact", "text": "If you have any questions about these Terms & Conditions, you can contact us at:" } } };
const meta$1 = { "about": { "title": "About Nomadic Digital — Strategy, Design & Engineering", "description": "Nomadic Digital is a digital studio focused on strategy, design, and scalable engineering for modern businesses." }, "blog": { "title": "Blog — Insights, Strategy & Digital Craft", "description": "Stories, insights, and practical lessons from Nomadic Digital on strategy, design, and engineering." } };
const about$1 = { "pageTitle": "About us" };
const contact$1 = { "meta": { "title": "Contact — Nomadic Digital", "description": "Start a conversation with Nomadic Digital. Tell us about your project and we’ll get back with clear next steps." } };
const pricing$1 = { "title": "Pricing", "meta": { "description": "Transparent pricing for digital strategy, design, and development services." } };
const services$1 = { "meta": { "title": "Services", "description": "Digital strategy, design, development, automation, and custom solutions built for growth." } };
const home$1 = { "meta": { "title": "Digital Products, Platforms & Growth Systems", "description": "We design and build high-performance websites, platforms, and digital systems that scale with your business." } };
const en = {
  "nav.work": "Work",
  "nav.about": "About Us",
  "nav.services": "Services",
  "nav.contact": "Contact",
  "nav.bookCall": "Book a call",
  "nav.lang.en": "EN",
  "nav.lang.ro": "RO",
  "hero.kicker": "Nomadic Digital ® — Digital Studio",
  "hero.title.main": "We build digital experiences",
  "hero.title.muted": " that actually perform.",
  "hero.subtitle": "Strategy, design, and engineering for brands that value clarity, speed, and measurable outcomes.",
  "hero.cta.primary": "Start a project →",
  "hero.cta.secondary": "View selected work",
  "hero.footer": "© 2025 Nomadic Digital",
  "clients.title": "Our clients",
  "clients.subtitle": "(Selected client partnerships)",
  "home.projects.count": "Selected work",
  "home.projects.title": "Projects",
  "home.projects.description": "We’ve helped businesses across industries achieve their goals. Here are some of our recent projects.",
  "why.label": "Why choose us",
  "why.title1": "Proven results for every project,",
  "why.title2": "with a focus on design and functionality.",
  "why.subtitle": "We design with intent and build tools that make work easier — focused on clarity, performance, and results that last.",
  "why.overlay.text": "Your digital journey begins with a conversation.<br />Let's talk today.",
  "why.overlay.cta": "Let’s talk",
  "why.stat1.label": "Successful projects completed",
  "why.stat1.desc": "Websites, e-commerce platforms, mobile applications and complex integrations shipped for various businesses.",
  "why.stat2.label": "Client satisfaction",
  "why.stat2.desc": "Long-term partnerships built on clear communication and reliable delivery.",
  "services.kicker": "What we do",
  "services.heading": "Services",
  "services.categoriesLabel": "Categories",
  "services.showLess": "Show less",
  "services.01.title": "Web & E-commerce Platforms",
  "services.01.desc": "Fast, scalable websites and e-commerce platforms designed for performance, conversion, and long-term growth. Built cleanly, without unnecessary layers.",
  "services.01.cat.1": "Custom websites",
  "services.01.cat.2": "E-commerce (B2C / B2B)",
  "services.01.cat.3": "Performance optimization",
  "services.01.cat.4": "SEO-ready architecture",
  "services.01.cat.5": "Headless CMS",
  "services.01.cat.6": "Conversion-focused UX",
  "services.02.title": "SaaS & Custom Systems",
  "services.02.desc": "Robust internal tools, SaaS platforms, and dashboards where reliability, security, and maintainability matter more than trends.",
  "services.02.cat.1": "SaaS architecture",
  "services.02.cat.2": "Admin dashboards",
  "services.02.cat.3": "ERP Integrations",
  "services.02.cat.4": "Stock Sync & Management",
  "services.02.cat.5": "Role-based access",
  "services.02.cat.6": "Payments & subscriptions",
  "services.02.cat.7": "API integrations",
  "services.02.cat.8": "Scalable backends",
  "services.03.title": "UX, Brand & Product Design",
  "services.03.desc": "Design systems and interfaces that remove friction, communicate clearly, and feel intentional across every touchpoint.",
  "services.03.cat.1": "UX & UI design",
  "services.03.cat.2": "Product structure",
  "services.03.cat.3": "Design systems",
  "services.03.cat.4": "Brand identity",
  "services.03.cat.5": "Visual language",
  "services.03.cat.6": "Usability testing",
  "services.04.title": "Marketing, SEO & Growth",
  "services.04.desc": "Focused marketing strategies built around measurable outcomes visibility, acquisition, and sustainable growth.",
  "services.04.cat.1": "SEO strategy",
  "services.04.cat.2": "Content marketing",
  "services.04.cat.3": "Paid ads (Google / Meta)",
  "services.04.cat.4": "Analytics & tracking",
  "services.04.cat.5": "Conversion optimization",
  "services.04.cat.6": "Growth experiments",
  "services.04.cat.7": "Local Advertising",
  "services.05.title": "Mobile App Development",
  "services.05.desc": "Native and cross-platform mobile applications built for reliability, performance, and real-world usage not just demos.",
  "services.05.cat.1": "iOS & Android apps",
  "services.05.cat.2": "Cross-platform (Flutter / React Native)",
  "services.05.cat.3": "App architecture",
  "services.05.cat.4": "API integrations",
  "services.05.cat.5": "Performance optimization",
  "services.05.cat.6": "App store deployment",
  "about.label": "About us",
  "about.brand": "Nomadic Digital ®",
  "about.titleBold": "How we launch",
  "about.titleRest": "websites and marketing campaigns.",
  "about.description": "See how our team combines creativity, technology, and strategy to build powerful digital solutions.",
  "how.steps.1.step": "STEP 1.",
  "how.steps.1.title": "Discovery Phase",
  "how.steps.1.desc": "Understanding your goals, pain points, audience, and what sets you apart.",
  "how.steps.2.step": "STEP 2.",
  "how.steps.2.title": "Project Kickoff",
  "how.steps.2.desc": "Aligning on scope, milestones, and setting a clear direction for execution.",
  "how.steps.3.step": "STEP 3.",
  "how.steps.3.title": "Receive & Refine",
  "how.steps.3.desc": "Reviewing work together, gathering feedback, and refining until it feels right.",
  "how.steps.4.step": "STEP 4.",
  "how.steps.4.title": "Continue & Grow",
  "how.steps.4.desc": "Launching confidently and supporting long-term growth and iteration.",
  "testimonials.eyebrow": "Testimonials",
  "testimonials.title": "Experiences",
  "testimonials.year": "©2025",
  "testimonials.summary.rating": "4.9",
  "testimonials.summary.text": "We’ve delivered 20+ projects that help companies generate real results.",
  "testimonials.cta.leaveReview": "Call Us",
  "testimonials.items.1.name": "Nicolae Curca",
  "testimonials.items.1.role": "Founder, Adedari",
  "testimonials.items.1.text": "A clear, professional corporate website that reflects our scale and values.",
  "testimonials.items.2.name": "Neil Ghura",
  "testimonials.items.2.role": "Founder, Natscent",
  "testimonials.items.2.text": "A premium e-commerce experience that balances brand storytelling and conversion.",
  "testimonials.items.3.name": "Ramona Simon",
  "testimonials.items.3.role": "Founder, Studio Urban & Kron Imobiliare",
  "testimonials.items.3.text": "Well-structured websites designed for real-world bookings and lead generation.",
  "stats.1.value": "10+",
  "stats.1.label": "Complex systems delivered",
  "stats.2.value": "20+",
  "stats.2.label": "Production integrations shipped",
  "stats.3.value": "99.9%",
  "stats.3.label": "Platform uptime across projects",
  "stats.4.value": "10+",
  "stats.4.label": "Industries served",
  "case.label": "Case study",
  "case.tags": "UX/UI Redesign, Frontend & Backend Optimization.",
  "case.description": "From branding to web development and marketing",
  "case.live": "Live website ↗",
  "case.performance.title": "Performance boost",
  "case.performance.conversionLabel": "Conversion rate",
  "case.performance.boost": "Page speed +48%, Bounce rate -23%",
  "case.performance.conversion": "4.2% → 13.9% (+231%)",
  "case.performance.testimonial": "The redesign led to a significant increase in website orders.",
  "case.performance.author": "Marina Slyusar",
  "case.scoreLabel": "Page speed score",
  "case.visitsLabel": "Quarterly visits",
  "case.month.dec": "Dec",
  "case.month.jan": "Jan",
  "case.month.feb": "Feb",
  "case.month.mar": "Mar",
  "case.month.apr": "Apr",
  "case.month.may": "May",
  "pricing.eyebrow": "Pricing",
  "pricing.title": "Clear pricing",
  "pricing.titleMuted": " for focused teams.",
  "pricing.subtitle": "Defined scopes, transparent costs, and engagements designed around real business needs.",
  "pricing.plan.starter.name": "Starter",
  "pricing.plan.starter.price": "€1,200",
  "pricing.plan.starter.subtitle": "For early-stage businesses",
  "pricing.plan.starter.features.1": "Website or landing page",
  "pricing.plan.starter.features.2": "UX/UI design",
  "pricing.plan.starter.features.3": "Responsive layout",
  "pricing.plan.starter.features.4": "Basic SEO setup",
  "pricing.plan.starter.cta": "Get started",
  "pricing.plan.pro.name": "Pro",
  "pricing.plan.pro.price": "€2,500",
  "pricing.plan.pro.subtitle": "Best value for growing teams",
  "pricing.plan.pro.features.1": "Everything in Starter",
  "pricing.plan.pro.features.2": "Custom integrations",
  "pricing.plan.pro.features.3": "Performance optimization",
  "pricing.plan.pro.features.4": "Advanced SEO & analytics",
  "pricing.plan.pro.features.5": "E-commerce websites (standard)",
  "pricing.plan.pro.features.6": "Mobile app development (simple apps: ordering, booking, MVP)",
  "pricing.plan.pro.features.7": "Priority support",
  "pricing.plan.pro.cta": "Start project",
  "pricing.plan.enterprise.name": "Enterprise",
  "pricing.plan.enterprise.price": "Custom",
  "pricing.plan.enterprise.subtitle": "Built around your business",
  "pricing.plan.enterprise.features.1": "Complex platforms & SaaS",
  "pricing.plan.enterprise.features.2": "Custom e-commerce solutions",
  "pricing.plan.enterprise.features.3": "ERP / API integrations",
  "pricing.plan.enterprise.features.4": "Automation workflows",
  "pricing.plan.enterprise.features.5": "Advanced mobile applications",
  "pricing.plan.enterprise.features.6": "Long-term partnership",
  "pricing.plan.enterprise.cta": "Talk to us",
  "team.eyebrow": "People",
  "team.titleA": "The team behind",
  "team.titleB": "the work.",
  "team.subtitle": "A small, focused team of designers, engineers, and strategists building durable digital products.",
  "team.member.stefan.role": "Founder & Lead Engineer",
  "team.member.stefan.desc": "System architecture, complex integrations, and hands-on development across platforms.",
  "team.member.teodora.role": "Client & Growth Manager",
  "team.member.teodora.desc": "Client relationships, project coordination, and growth-focused strategy execution.",
  "team.member.mihai.role": "Content & Strategy Consultant",
  "team.member.mihai.desc": "Content production, strategic consulting, and risk assessment across projects.",
  "team.member.dulca.role": "Lead Sales Consultant",
  "team.member.dulca.desc": "Managing outbound sales, client acquisition, and first-contact negotiations.",
  "faq.title": "FAQ",
  "faq.subtitle": "Got questions? We’ve got answers. Everything you need to know about working with us.",
  "faq.1.q": "How long does it take to build a website?",
  "faq.1.a": "The timeline depends on complexity and scope. Most projects take between 4–8 weeks. We provide a clear timeline during the initial consultation.",
  "faq.2.q": "Do you offer custom websites or use templates?",
  "faq.2.a": "All projects are custom-designed unless we decide otherwise together. But generally we don’t rely on generic templates — every solution is built around your business goals.",
  "faq.3.q": "What’s included in your SEO services?",
  "faq.3.a": "Our SEO services include technical optimization, keyword research, on-page improvements, performance tuning, and analytics setup.",
  "faq.4.q": "How does the monthly subscription model work?",
  "faq.4.a": "For ongoing services, we offer monthly subscriptions covering maintenance, optimization, and growth support. Plans are flexible and scalable.",
  "faq.5.q": "Can you redesign my existing website?",
  "faq.5.a": "Yes. We frequently redesign existing websites, improving UX, performance, and visual clarity while preserving your brand.",
  "faq.6.q": "How do I get started?",
  "faq.6.a": "Simply reach out through our contact form or Whatsapp at +40 747 754 180. We’ll schedule a discovery call to understand your needs and propose the next steps.",
  "blog.section.titleA": "Newest trends",
  "blog.section.titleB": " and insights from our team.",
  "blog.section.subtitle": "Stay informed about our latest projects, trends, and industry insights.",
  "blog.section.cta": "See all",
  "contact.brand": "Nomadic Digital ®",
  "contact.form.title": "Have a project in mind?",
  "contact.form.name": "Your name",
  "contact.form.email": "E-mail",
  "contact.form.message": "Tell us about your project",
  "contact.form.sending": "Sending…",
  "contact.form.send": "Send message",
  "contact.error.required": "Please fill in all fields.",
  "contact.error.generic": "Failed to send message.",
  "contact.success": "Message sent successfully. We’ll get back to you shortly.",
  "contact.legal": "By submitting, you agree to our Terms & Privacy Policy.",
  "contact.title": "Let’s talk.",
  "contact.subtitle": "Tell us about your project, whether it’s a website, ERP system integration, mobile app, or marketing.",
  "contact.benefit1.title": "Quick response",
  "contact.benefit1.text": "We reply quickly and keep communication simple and direct.",
  "contact.benefit2.title": "Clear next steps",
  "contact.benefit2.text": "You’ll receive a concrete plan, scope, and timeline.",
  "contact.card.role": "Client & Growth Manager",
  "contact.card.name": "Teodora Szelyes",
  "contact.card.cta": "Ask directly",
  "footer.desc": "We design and build high-performance digital products — websites, platforms, and marketing systems that scale.",
  "footer.company": "Company",
  "footer.company.about": "About",
  "footer.company.work": "Work",
  "footer.company.pricing": "Pricing",
  "footer.company.contact": "Contact",
  "footer.services": "Services",
  "footer.services.1": "Web Design",
  "footer.services.2": "Web Development",
  "footer.services.3": "SEO & Performance",
  "footer.services.4": "Brand Strategy",
  "footer.follow": "Follow",
  "footer.follow.instagram": "Instagram",
  "footer.follow.facebook": "Facebook",
  "footer.follow.linkedin": "LinkedIn",
  "footer.follow.x": "Twitter / X",
  "footer.copyright": "© {year} Nomadic Digital ® . All rights reserved.",
  "footer.cta": "Start a project",
  "footer.privacy": "Privacy Policy",
  "footer.terms": "Terms & Conditions",
  "footer.logoAlt": "Nomadic Digital logo",
  "about.pageTitle": "About us",
  "about.studio": "Studio",
  "about.hero.bold": "We build digital products with clarity, restraint, and purpose.",
  "about.hero.sub": "Every decision is intentional — from structure and performance to how a brand feels when someone uses it.",
  "about.hero.socialProof": "Trusted by founders, operators, and growing teams worldwide",
  "about.hero.note": "No noise. No unnecessary layers. Just well-crafted digital work that holds up over time.",
  "about.hero.imageAlt": "Studio collaboration",
  "about.approach.kicker": "Every project we take on is designed for long-term success.",
  "about.approach.line1": "Our approach is simple:",
  "about.approach.line2": "functionality, speed, and clarity,",
  "about.approach.line3": "without unnecessary complexity.",
  "about.approach.body": "We don’t overpromise. We build durable, thoughtful digital products that scale with real business needs.",
  "about.approach.cta": "Portfolio",
  "about.difference.title": "What sets us apart",
  "about.difference.subtitle": "Not louder. Not bigger. Just sharper where it matters.",
  "about.difference.bold": "We don’t sell services.",
  "about.difference.rest": "We solve specific business problems with focused, intentional digital work.",
  "about.difference.body": "No bloated scopes. No unnecessary layers. Every line of code, every design choice, and every integration exists for a reason — to perform, scale, and last.",
  "about.difference.cta": "Get in touch",
  "about.editorial.1.title": "Meet the team",
  "about.editorial.2.title": "How work gets done",
  "services.pageTitle": "Services",
  "services.capabilities": "Capabilities",
  "services.hero.bold": "We design and build digital systems that support real growth.",
  "services.hero.sub": "From strategy and UX to complex development and integrations, our work is focused on clarity, performance, and long-term value.",
  "services.hero.note": "We don’t offer generic packages. Every engagement is shaped around the business problem, the product, and the stage you’re at.",
  "services.hero.right": "Strategy-led. Outcome-driven. Built to last.",
  "services.hero.imageAlt": "Studio collaboration",
  "services.01.kicker": "Web & E-commerce Platforms",
  "services.01.headline": "Fast, scalable platforms built for conversion.",
  "services.01.body": "We design and develop modern websites and e-commerce platforms that load fast, scale cleanly, and support both marketing and operations.",
  "services.01.points.1": "Custom storefronts",
  "services.01.points.2": "B2C & B2B flows",
  "services.01.points.3": "Performance optimization",
  "services.01.points.4": "SEO-ready architecture",
  "services.02.kicker": "SaaS & Custom Systems",
  "services.02.headline": "Complex products, clean architecture.",
  "services.02.body": "We build internal tools, SaaS platforms, and custom dashboards where reliability, security, and maintainability matter.",
  "services.02.points.1": "Admin dashboards",
  "services.02.points.2": "Role-based systems",
  "services.02.points.3": "Payments & subscriptions",
  "services.02.points.4": "Scalable backend logic",
  "services.02.points.5": "ERP integrations",
  "services.02.points.6": "Complex API integrations",
  "services.03.kicker": "UX, Brand & Product Design",
  "services.03.headline": "Design that removes friction.",
  "services.03.body": "We design interfaces and brand systems that feel intentional, clear, and aligned with how users actually behave.",
  "services.03.points.1": "UX & UI design",
  "services.03.points.2": "Product structure",
  "services.03.points.3": "Brand systems",
  "services.03.points.4": "Design systems",
  "services.03.points.5": "Print & on-demand production",
  "services.03.points.6": "Physical brand assets (cards, apparel, packaging)",
  "services.04.kicker": "Marketing & Growth",
  "services.04.headline": "Marketing built on data, not assumptions.",
  "services.04.body": "We plan and execute marketing systems that support growth long-term — aligned with product, infrastructure, and real business constraints.",
  "services.04.points.1": "Performance marketing",
  "services.04.points.2": "SEO & content strategy",
  "services.04.points.3": "Analytics & conversion tracking",
  "services.04.points.4": "Campaign structure & optimization",
  "services.05.kicker": "Mobile App Development",
  "services.05.headline": "Mobile apps built for real-world usage.",
  "services.05.body": "We design and develop mobile applications that are reliable, performant, and easy to maintain — focused on long-term usability, not short-term demos.",
  "services.05.points.1": "iOS & Android applications",
  "services.05.points.2": "Cross-platform development (Flutter / React Native)",
  "services.05.points.3": "API & backend integration",
  "services.05.points.4": "Performance & scalability optimization",
  "services.05.points.5": "App Store & Play Store deployment",
  "services.highlights.1.tag": "Engineering",
  "services.highlights.1.title": "Scalable systems",
  "services.highlights.1.desc": "Architecture designed to grow with your business.",
  "services.highlights.2.tag": "UX / UI",
  "services.highlights.2.title": "Clear product design",
  "services.highlights.2.desc": "Interfaces that reduce friction and increase conversion.",
  "services.bottomCta.title": "Have a specific problem to solve?",
  "services.bottomCta.sub": "If you’re unsure which service fits best, we’ll help you figure it out.",
  "services.bottomCta.button": "Start a conversation",
  "contact.hero.imageAlt": "Background image",
  "contact.hero.eyebrow": "Start a conversation",
  "contact.hero.title": "Let’s build something",
  "contact.hero.titleMuted": "meaningful.",
  "contact.hero.subtitle": "Websites, e-commerce, mobile apps, and growth strategies — built with clarity, performance, and long-term value in mind.",
  "contact.left.kicker": "Contact",
  "contact.left.title": "Let’s talk.",
  "contact.left.description": "Tell us about your project. We’ll get back with clear next steps, no obligations.",
  "contact.left.emailLabel": "Email",
  "contact.left.responseLabel": "Response time",
  "contact.left.responseValue": "Usually within 48 hours",
  "contact.form.nameLabel": "Name",
  "contact.form.namePlaceholder": "Your name",
  "contact.form.emailLabel": "Email",
  "contact.form.emailPlaceholder": "you@email.com",
  "contact.form.messageLabel": "Message",
  "contact.form.messagePlaceholder": "Tell us a bit about your project",
  "contact.form.success": "Message sent successfully. We’ll be in touch.",
  "contact.form.privacyNote": "By submitting this form you agree to our Privacy Policy.",
  "contact.form.genericError": "Something went wrong",
  portfolioPageTitle: portfolioPageTitle$1,
  portfolio: portfolio$1,
  blog: blog$1,
  privacy: privacy$1,
  terms: terms$1,
  meta: meta$1,
  about: about$1,
  contact: contact$1,
  pricing: pricing$1,
  services: services$1,
  home: home$1
};
const portfolioPageTitle = "Portofoliu";
const portfolio = { "pageTitle": "Portofoliu", "meta": { "client": "Client", "category": "Categorie", "year": "An", "status": "Status", "title": "Portfoliu — Nomadic Digital", "description": "Explorează proiecte selectate și produse digitale create de Nomadic Digital." }, "sections": { "scope": "Scope", "deliverables": "Livrabile", "technology": "Tehnologie" }, "cta": { "startSimilar": "Începe un proiect similar" }, "status": { "live": "Live", "inProgress": "În lucru", "completed": "Finalizat" }, "categories": { "ecommerceBrandPlatform": "E-commerce · Platformă de brand", "saasDigitalAdvertising": "SaaS · Publicitate digitală", "corporateWebsite": "Website corporate", "saasSportsManagement": "SaaS · Management sport", "ecommerceBrandWebsite": "E-commerce · Website de brand", "corporateBrandWebsite": "Corporate · Website de brand" }, "scope": { "platformArchitecture": "Arhitectură platformă", "uxUiDesign": "Design UX / UI", "ecommerceDevelopment": "Dezvoltare e-commerce", "erpApiIntegrations": "Integrări ERP & API", "performanceOptimization": "Optimizare performanță", "saasArchitecture": "Arhitectură SaaS", "adminDashboard": "Dashboard admin", "tabletInterface": "Interfață tabletă", "reportingAnalytics": "Raportare & analytics", "roleBasedAccess": "Acces pe roluri", "websiteDevelopment": "Dezvoltare website", "seoStructure": "Structură SEO", "memberManagement": "Management membri", "paymentFlows": "Fluxuri de plată", "mobileFirstUx": "UX mobile-first", "brandUx": "Brand UX", "productPresentation": "Prezentare produse", "seoOptimization": "Optimizare SEO", "websiteRedesign": "Redesign website", "contentStructure": "Structură conținut", "brandPresentation": "Prezentare brand", "automation": "Automatizare Procese" }, "deliverables": { "customStorefront": "Storefront custom", "adminDashboard": "Dashboard admin", "productStockSync": "Sincronizare produse & stoc", "seoReadyStructure": "Structură SEO-ready", "analyticsSetup": "Setare analytics", "webAdminPlatform": "Platformă web admin", "tabletUi": "Interfață tabletă", "campaignReporting": "Raportare campanii", "clientDashboards": "Dashboard-uri clienți", "corporateWebsite": "Website corporate", "responsiveLayouts": "Layout-uri responsive", "seoReadyPages": "Pagini SEO-ready", "webAdminPanel": "Panou web admin", "memberDashboard": "Dashboard membri", "paymentSystem": "Sistem de plăți", "classScheduling": "Programare clase", "productPages": "Pagini de produs", "contentDrivenLayout": "Layout orientat pe conținut", "multilingualStructure": "Structură multilingvă", "automatedInvoicing": "Facturare automată", "mobileDevelopment": "Dezvoltare mobilă" }, "metrics": { "pageSpeed": "Viteză pagină", "conversionRate": "Rată de conversie", "bounceRate": "Rată de respingere", "activeScreens": "Ecrane active", "monthlyImpressions": "Impresii lunare", "clubsOnboarded": "Cluburi înscrise", "activeMembers": "Membri activi" }, "roles": { "ecommerceOperations": "E-commerce & Operațiuni" }, "projects": { "conte": { "demos": { "stock": { "title": "Sincronizare stoc în timp real", "body": "Actualizare automată a stocurilor între platforma Shopify și sistemul ERP, asigurând disponibilitate corectă pe toate canalele, fără intervenție manuală." }, "dashboard": { "title": "Experiență e-commerce orientată spre conversie", "body": "Fluxuri și interfețe optimizate pentru a reduce fricțiunea, a ghida deciziile de cumpărare și a îmbunătăți performanța conversiilor și a checkout-ului." }, "uiux": { "title": "Optimizare UX & UI", "body": "Îmbunătățiri de interfață axate pe claritate, utilizabilitate și conversie, menținând în același timp o experiență premium de brand." }, "platform": { "title": "Arhitectură platformă e-commerce", "body": "O arhitectură Shopify scalabilă, configurată pentru a susține fluxuri B2C și B2B, performanță ridicată și creștere pe termen lung." } }, "overview": { "headline": "Un ecosistem e-commerce Shopify optimizat pentru scalare.", "description": "Conte avea nevoie de un setup Shopify solid, integrat strâns cu sistemul ERP și operațiunile B2B, care să susțină automatizarea, creșterea și repoziționarea brandului." }, "outcomes": { "headline": "Claritate operațională, automatizare și creștere scalabilă.", "description": "Munca manuală a fost redusă prin integrări ERP și B2B, instrumentele interne au eficientizat operațiunile zilnice, iar rebrandul a fost implementat coerent pe toate canalele digitale." }, "testimonial": { "quote": "Integrările și automatizarea ne-au schimbat fundamental modul de lucru, oferindu-ne stabilitate și spațiu real de creștere." } }, "locallia": { "demos": { "dashboard": { "title": "Dashboard campanii & dispozitive", "body": "Panou central pentru administrarea campaniilor, dispozitivelor și afișărilor în rețea." }, "analytics": { "title": "Raportare & analytics", "body": "Raportare transparentă care transformă expunerea fizică în date clare și măsurabile." }, "platform": { "title": "Arhitectură platformă SaaS", "body": "Fundație SaaS scalabilă pentru management multi-client și extindere viitoare." } }, "overview": { "headline": "O platformă de publicitate locală, cu impact în lumea reală.", "description": "Locallia conectează brandurile cu audiențe locale prin publicitate inteligentă și raportare bazată pe date." }, "outcomes": { "headline": "Transformă reach-ul fizic în performanță măsurabilă.", "description": "Platforma permite raportare în timp real, management scalabil al dispozitivelor și decizii bazate pe date." } }, "kronburg": { "demos": { "uiux": { "title": "Design UX & UI corporate", "body": "Interfață sobru-profesională, construită pentru claritate, structură și încredere." }, "website": { "title": "Website corporate", "body": "Website rapid și SEO-ready, orientat pe comunicare clară și mentenanță pe termen lung." } }, "overview": { "headline": "O prezență corporate curată, construită pe claritate și încredere.", "description": "Kronburg avea nevoie de un website profesional care să comunice fiabilitate fără zgomot vizual." }, "outcomes": { "headline": "O prezență digitală construită pe încredere.", "description": "Mesaj de brand clar, performanță ridicată și structură SEO solidă." } }, "fluxum": { "demos": { "dashboard": { "title": "Dashboard club & administrare", "body": "Panou central pentru managementul membrilor, claselor, plăților și comunicării." }, "payments": { "title": "Plăți & abonamente", "body": "Sistem de plăți recurente și abonamente adaptat cluburilor sportive." }, "platform": { "title": "Arhitectură SaaS", "body": "Platformă scalabilă pentru mai multe cluburi, roluri și funcționalități viitoare." } }, "overview": { "headline": "O platformă modernă pentru managementul cluburilor sportive.", "description": "Fluxum simplifică abonamentele, plățile, programările și comunicarea." }, "outcomes": { "headline": "Operațiuni simplificate într-un singur sistem.", "description": "Reducerea muncii administrative și îmbunătățirea experienței zilnice pentru administratori și membri." } }, "natscent": { "demos": { "uiux": { "title": "UX editorial & identitate vizuală", "body": "Interfață calmă, orientată pe storytelling și conversie." }, "ecommerce": { "title": "Storefront e-commerce", "body": "Experiență de cumpărare fluidă, optimizată pentru descoperirea produselor." } }, "overview": { "headline": "O experiență e-commerce rafinată pentru un brand de parfumuri.", "description": "Un storefront editorial care echilibrează povestea și conversia." }, "outcomes": { "headline": "Un storefront editorial gândit pentru conversie.", "description": "Branding puternic combinat cu un flux de cumpărare eficient." } }, "viorica": { "demos": { "erpSync": { "title": "Sincronizare produse și stoc cu ERP", "body": "Sincronizare automată între platforma online și sistemul ERP pentru produse, stocuri și prețuri, menținând datele consistente între sisteme." }, "orderAutomation": { "title": "Automatizare procesare comenzi", "body": "Comenzile plasate online sunt trimise automat către ERP, reducând munca manuală, erorile operaționale și timpii de procesare." } }, "overview": { "headline": "Integrare ERP și automatizare operațională pentru un brand de cosmetice.", "description": "Viorica avea nevoie de o integrare stabilă între magazinul online și sistemul ERP pentru a eficientiza operațiunile și a asigura acuratețea datelor." }, "outcomes": { "headline": "Operațiuni mai eficiente prin automatizare ERP.", "description": "Integrarea a eliminat procesele manuale repetitive și a asigurat un flux de date coerent între e-commerce și ERP." } } } };
const blog = { "pageTitle": "Blog", "index": { "title": "Noutați din blog", "subtitle": "Insight-uri, studii de caz și lecții învățate din proiectele noastre recente." }, "roles": { "productStrategist": "Strateg produs", "uiuxDesigner": "Designer UI/UX", "securityLead": "Responsabil securitate", "cfoCoFounder": "CFO & co-fondator", "growthAnalyst": "Analist growth" }, "posts": { "metricsForSaas": { "title": "5 metrici pe care orice fondator SaaS ar trebui să le urmărească", "description": "Află ce KPI-uri contează când scalezi un SaaS.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Înțelegerea numerelor</h2><p class="font-[550]">Să știi ce să măsori este esențial atunci când crești un produs. Metrici precum churn, valoarea pe durata de viață a clientului (LTV) și costul de achiziție (CAC) oferă perspective puternice despre sănătatea businessului. Fără aceste numere, deciziile devin simple presupuneri.</p></div><div><h2 class="text-2xl font-semibold mb-3">Metricile care contează</h2><p class="font-[550]">Deși există multe metrici posibile, nu toate au aceeași greutate. Prioritizează engagement-ul, ratele de conversie și utilizarea funcțiilor pentru a înțelege cum livrează produsul valoare. Acești indicatori te ghidează spre acțiuni cu impact.</p></div><div><h2 class="text-2xl font-semibold mb-3">Aplicarea insight-urilor</h2><p class="font-[550]">Urmărirea metricilor este doar jumătate din ecuație—mai important este ce faci cu ele. Folosește datele ca să validezi idei, să îmbunătățești experiența utilizatorilor și să identifici oportunități. Revizuirile regulate duc la decizii mai bune și creștere mai focusată.</p></div></div>' }, "simplerDashboard": { "title": "Cum am proiectat o experiență de dashboard mai simplă", "description": "O privire din culise asupra modului în care am construit un dashboard clar, rapid și orientat către utilizator.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Provocări de design</h2><p class="font-[550]">Am început prin a identifica elementele cele mai confuze din dashboard-ul actual...</p></div><div><h2 class="text-2xl font-semibold mb-3">Simplificarea interfeței</h2><p class="font-[550]">Prin testare și feedback, am rafinat structura pentru a crește claritatea și a reduce aglomerația...</p></div></div>' }, "secureSyncing": { "title": "De ce sincronizarea sigură contează mai mult ca niciodată", "description": "Vezi cum abordarea noastră security-first îți protejează datele și îți oferă liniște.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Riscurile datelor nesigure</h2><p class="font-[550]">Sincronizarea datelor poate expune vulnerabilități dacă nu este făcută corect...</p></div><div><h2 class="text-2xl font-semibold mb-3">Cum securizăm sincronizarea</h2><p class="font-[550]">Folosim criptare end-to-end și controale stricte de acces pentru ca doar utilizatorii autorizați să poată vedea date sensibile...</p></div></div>' }, "scalingFinance": { "title": "Cum scalezi finanțele unui startup fără stres", "description": "Strategii și instrumente practice pentru a-ți gestiona finanțele pe măsură ce crești.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Igiena financiară</h2><p class="font-[550]">Chiar și în stadiile incipiente, igiena financiară de bază este critică...</p></div><div><h2 class="text-2xl font-semibold mb-3">Instrumente pentru scalare</h2><p class="font-[550]">Recomandăm instrumente de forecasting automatizat și dashboard-uri clare pentru cash flow...</p></div></div>' }, "lessons10k": { "title": "Ce am învățat de la peste 10.000 de utilizatori", "description": "Insight-uri reale care modelează direcția viitoare a produsului nostru.", "content": '<div class="space-y-10 text-gray-800 text-[15px] leading-relaxed"><div><h2 class="text-2xl font-semibold mb-3">Insight-uri din comportamentul utilizatorilor</h2><p class="font-[550]">De la onboarding până la utilizarea pe termen lung, am urmărit trenduri care au scos la iveală nevoi neașteptate...</p></div><div><h2 class="text-2xl font-semibold mb-3">Adaptarea produsului</h2><p class="font-[550]">Am făcut schimbări pe baza acestor observații, inclusiv simplificarea înscrierii și îmbunătățirea vizibilității suportului...</p></div></div>' } } };
const privacy = { "meta": { "title": "Politica de Confidențialitate — Nomadic Digital", "description": "Află cum Nomadic Digital colectează, utilizează și protejează datele tale personale, conform GDPR." }, "title": "Politica de confidențialitate", "lastUpdated": "Ultima actualizare: {date}", "intro": "<b>Nomadic Digital</b> („noi”, „al nostru”) respectă confidențialitatea ta. Această politică explică modul în care colectăm, utilizăm și protejăm informațiile tale atunci când vizitezi website-ul nostru sau ne contactezi prin formulare.", "sections": { "collect": { "title": "1. Informații colectate", "text": "Putem colecta informații personale furnizate voluntar, inclusiv:", "items": { "name": "Nume", "email": "Adresă de email", "message": "Conținutul mesajului", "optional": "Orice alte informații pe care alegi să le furnizezi" } }, "usage": { "title": "2. Cum folosim informațiile tale", "text": "Folosim informațiile colectate exclusiv pentru:", "items": { "reply": "A răspunde solicitărilor și mesajelor", "projects": "A comunica despre proiecte sau servicii potențiale", "improve": "Îmbunătățirea website-ului și a serviciilor noastre" }, "note": "Nu vindem, nu închiriem și nu distribuim datele tale personale." }, "security": { "title": "3. Stocarea și securitatea datelor", "text": "Aplicăm măsuri tehnice și organizatorice rezonabile pentru a proteja datele tale. Mesajele trimise prin formularul de contact sunt transmise în siguranță și accesibile doar personalului autorizat." }, "cookies": { "title": "4. Cookie-uri și analiză", "text": "Website-ul poate utiliza instrumente de analiză de bază pentru a înțelege traficul și utilizarea. Acestea colectează date anonime, agregate și nu permit identificarea personală." }, "rights": { "title": "5. Drepturile tale (GDPR)", "text": "Dacă te afli în Uniunea Europeană, ai dreptul să:", "items": { "access": "Soliciți acces la datele tale personale", "modify": "Soliciți corectarea sau ștergerea datelor", "withdraw": "Îți retragi consimțământul în orice moment" } }, "contact": { "title": "6. Contact", "text": "Pentru orice întrebări legate de această politică sau de modul în care gestionăm datele tale, ne poți contacta la:" } } };
const terms = { "meta": { "title": "Termeni și Condiții — Nomadic Digital", "description": "Citește termenii și condițiile care reglementează utilizarea site-ului și serviciilor Nomadic Digital." }, "title": "Termeni și condiții", "lastUpdated": "Ultima actualizare: {date}", "intro": "Acești Termeni și condiții reglementează utilizarea website-ului și a serviciilor Nomadic Digital. Prin accesarea acestui site sau contactarea noastră, ești de acord cu acești termeni.", "sections": { "about": { "title": "1. Despre noi", "text": "Nomadic Digital oferă servicii digitale precum web design, dezvoltare, branding, SEO și strategie de marketing. Informațiile de pe acest site sunt furnizate exclusiv în scop informativ." }, "usage": { "title": "2. Utilizarea website-ului", "text": "Ești de acord să utilizezi acest website doar în scopuri legale. Este interzis să:", "items": { "access": "Încerci să obții acces neautorizat la website sau sisteme", "damage": "Folosești website-ul într-un mod care poate afecta funcționalitatea", "copy": "Copiezi sau reutilizezi conținutul fără permisiune" } }, "services": { "title": "3. Servicii și oferte", "text": "Orice servicii oferite sunt supuse unui acord, unei propuneri sau unui contract separat. Trimiterea unui formular de contact nu creează o obligație contractuală." }, "ip": { "title": "4. Proprietate intelectuală", "text": "Întregul conținut al acestui website — inclusiv texte, elemente vizuale, branding și structură — aparține Nomadic Digital, dacă nu se specifică altfel. Reproducerea sau distribuirea fără acord scris este interzisă." }, "liability": { "title": "5. Limitarea răspunderii", "text": "Depunem eforturi rezonabile pentru a menține informațiile actualizate și corecte, însă nu garantăm exhaustivitatea acestora. Nu ne asumăm răspunderea pentru eventuale daune rezultate din utilizarea sau imposibilitatea utilizării website-ului." }, "links": { "title": "6. Linkuri externe", "text": "Website-ul poate conține linkuri către site-uri terțe. Nu suntem responsabili pentru conținutul sau practicile acestora." }, "changes": { "title": "7. Modificări ale termenilor", "text": "Ne rezervăm dreptul de a actualiza acești Termeni și condiții. Orice modificare va fi publicată pe această pagină, împreună cu data actualizării." }, "contact": { "title": "8. Contact", "text": "Pentru orice întrebări legate de acești Termeni și condiții, ne poți contacta la:" } } };
const meta = { "about": { "title": "Despre Nomadic Digital — Strategie, Design și Inginerie", "description": "Nomadic Digital este un studio digital axat pe strategie, design și dezvoltare scalabilă pentru afaceri moderne." }, "blog": { "title": "Blog — Insight-uri, Strategie și Digital", "description": "Articole, idei și lecții practice de la Nomadic Digital despre strategie, design și dezvoltare." } };
const about = { "pageTitle": "Despre noi" };
const contact = { "meta": { "title": "Contact — Nomadic Digital", "description": "Începe o conversație cu Nomadic Digital. Spune-ne despre proiectul tău și revenim cu următorii pași." } };
const pricing = { "title": "Prețuri", "meta": { "description": "Structuri de preț transparente pentru servicii digitale, design și dezvoltare." } };
const services = { "meta": { "title": "Servicii", "description": "Strategie digitală, design, dezvoltare, automatizări și soluții personalizate pentru creștere." } };
const home = { "meta": { "title": "Produse Digitale, Platforme și Sisteme de Creștere", "description": "Proiectăm și dezvoltăm website-uri, platforme și sisteme digitale performante care cresc odată cu afacerea ta." } };
const ro = {
  "nav.work": "Portofoliu",
  "nav.about": "Despre noi",
  "nav.services": "Servicii",
  "nav.contact": "Contact",
  "nav.bookCall": "Programează un apel",
  "nav.lang.en": "EN",
  "nav.lang.ro": "RO",
  "hero.kicker": "Nomadic Digital ® — Studio Digital",
  "hero.title.main": "Construim experiențe digitale",
  "hero.title.muted": " care chiar performează.",
  "hero.subtitle": "Strategie, design și dezvoltare pentru branduri care vor claritate, viteză și creștere măsurabilă.",
  "hero.cta.primary": "Începe un proiect →",
  "hero.cta.secondary": "Vezi proiecte selectate",
  "hero.footer": "© 2025 Nomadic Digital",
  "clients.title": "Clienții noștri",
  "clients.subtitle": "(Parteneriate selectate)",
  "home.projects.count": "Proiecte selectate",
  "home.projects.title": "Proiecte",
  "home.projects.description": "Am ajutat business-uri din industrii diferite să-și atingă obiectivele. Iată câteva proiecte recente.",
  "why.label": "De ce noi",
  "why.title1": "Rezultate dovedite pentru fiecare proiect,",
  "why.title2": "cu focus pe design și funcționalitate.",
  "why.subtitle": "Proiectăm cu intenție și construim soluții care simplifică munca — cu focus pe claritate, performanță și rezultate care rezistă.",
  "why.overlay.text": "Drumul tău digital începe cu o conversație.<br />Hai să vorbim azi.",
  "why.overlay.cta": "Hai să vorbim",
  "why.stat1.label": "Proiecte livrate cu succes",
  "why.stat1.desc": "Website-uri, platforme e-commerce și integrări complexe livrate pentru business-uri reale.",
  "why.stat2.label": "Satisfacția clienților",
  "why.stat2.desc": "Parteneriate pe termen lung, construite pe comunicare clară și livrare predictibilă.",
  "services.kicker": "Ce facem",
  "services.heading": "Servicii",
  "services.categoriesLabel": "Categorii",
  "services.showLess": "Arată mai puțin",
  "services.01.title": "Platforme Web & E-commerce",
  "services.01.desc": "Website-uri rapide, scalabile și platforme e-commerce construite pentru performanță, conversie și creștere pe termen lung. Fără straturi inutile.",
  "services.01.cat.1": "Website-uri custom",
  "services.01.cat.2": "E-commerce (B2C / B2B)",
  "services.01.cat.3": "Optimizare performanță",
  "services.01.cat.4": "Arhitectură SEO-ready",
  "services.01.cat.5": "Headless CMS",
  "services.01.cat.6": "UX orientat pe conversie",
  "services.02.title": "SaaS & Sisteme Custom",
  "services.02.desc": "Tool-uri interne, platforme SaaS și dashboard-uri unde contează fiabilitatea, securitatea și mentenanța — nu trendurile.",
  "services.02.cat.1": "Arhitectură SaaS",
  "services.02.cat.2": "Dashboard-uri admin",
  "services.02.cat.3": "Integrări ERP",
  "services.02.cat.4": "Sync & management stoc",
  "services.02.cat.5": "Acces pe roluri",
  "services.02.cat.6": "Plăți & abonamente",
  "services.02.cat.7": "Integrări API",
  "services.02.cat.8": "Backend-uri scalabile",
  "services.03.title": "UX, Brand & Product Design",
  "services.03.desc": "Design systems și interfețe care reduc fricțiunea, comunică clar și se simt intenționate în fiecare punct de contact.",
  "services.03.cat.1": "Design UX & UI",
  "services.03.cat.2": "Structură produs",
  "services.03.cat.3": "Design systems",
  "services.03.cat.4": "Identitate de brand",
  "services.03.cat.5": "Limbaj vizual",
  "services.03.cat.6": "Testare de utilizabilitate",
  "services.04.title": "Marketing, SEO & Growth",
  "services.04.desc": "Strategii de marketing construite pe rezultate măsurabile — vizibilitate, achiziție și creștere sustenabilă.",
  "services.04.cat.1": "Strategie SEO",
  "services.04.cat.2": "Content marketing",
  "services.04.cat.3": "Reclame plătite (Google / Meta)",
  "services.04.cat.4": "Analytics & tracking",
  "services.04.cat.5": "Optimizare conversie",
  "services.04.cat.6": "Experimente de growth",
  "services.04.cat.7": "Publicitate locală",
  "services.05.title": "Dezvoltare Aplicații Mobile",
  "services.05.desc": "Aplicații mobile native și cross-platform construite pentru fiabilitate, performanță și utilizare reală — nu demo-uri.",
  "services.05.cat.1": "Aplicații iOS & Android",
  "services.05.cat.2": "Cross-platform (Flutter / React Native)",
  "services.05.cat.3": "Arhitectură aplicație",
  "services.05.cat.4": "Integrări API",
  "services.05.cat.5": "Optimizare performanță",
  "services.05.cat.6": "Publicare în App Store",
  "about.label": "Despre noi",
  "about.brand": "Nomadic Digital ®",
  "about.titleBold": "Cum lansăm",
  "about.titleRest": "website-uri și campanii de marketing.",
  "about.description": "Vezi cum combinăm creativitatea, tehnologia și strategia pentru a construi soluții digitale cu impact.",
  "how.steps.1.step": "PASUL 1.",
  "how.steps.1.title": "Faza de descoperire",
  "how.steps.1.desc": "Înțelegem obiectivele, provocările, publicul și ce te diferențiază.",
  "how.steps.2.step": "PASUL 2.",
  "how.steps.2.title": "Start proiect",
  "how.steps.2.desc": "Aliniem scope-ul, etapele și stabilim o direcție clară pentru execuție.",
  "how.steps.3.step": "PASUL 3.",
  "how.steps.3.title": "Revizuim & rafinăm",
  "how.steps.3.desc": "Revizuim împreună, colectăm feedback și rafinăm până arată exact cum trebuie.",
  "how.steps.4.step": "PASUL 4.",
  "how.steps.4.title": "Continuăm & creștem",
  "how.steps.4.desc": "Lansăm cu încredere și susținem creșterea pe termen lung și iterațiile.",
  "testimonials.eyebrow": "Testimoniale",
  "testimonials.title": "Experiențe",
  "testimonials.year": "©2025",
  "testimonials.summary.rating": "4,9",
  "testimonials.cta.leaveReview": "Scrie-ne",
  "testimonials.summary.text": "Proiecte livrate pentru companii care pun accent pe claritate și execuție.",
  "testimonials.items.1.name": "Nicolae Curca",
  "testimonials.items.1.role": "Fondator, Adedari",
  "testimonials.items.1.text": "Un website corporate clar și profesionist, care reflectă dimensiunea și valorile companiei.",
  "testimonials.items.2.name": "Neil Ghura",
  "testimonials.items.2.role": "Fondator, Natscent",
  "testimonials.items.2.text": "O experiență e-commerce premium, echilibrată între storytelling și conversie.",
  "testimonials.items.3.name": "Ramona Simon",
  "testimonials.items.3.role": "Fondator, Studio Urban & Kron Imobiliare",
  "testimonials.items.3.text": "Website-uri bine structurate, gândite pentru rezervări și lead-uri reale.",
  "stats.1.value": "10+",
  "stats.1.label": "Sisteme complexe livrate",
  "stats.2.value": "20+",
  "stats.2.label": "Integrări în producție",
  "stats.3.value": "99,9%",
  "stats.3.label": "Uptime pe proiecte active",
  "stats.4.value": "10+",
  "stats.4.label": "Industrii deservite",
  "case.label": "Studiu de caz",
  "case.tags": "Redesign UX/UI, Optimizare Frontend.",
  "case.description": "De la branding la dezvoltare web și marketing",
  "case.live": "Website live ↗",
  "case.performance.title": "Creștere performanță",
  "case.performance.conversionLabel": "Rată de conversie",
  "case.performance.boost": "Viteză pagină +48%, Bounce rate -23%",
  "case.performance.conversion": "4,2% → 13,9% (+231%)",
  "case.performance.testimonial": "Redesign-ul a dus la o creștere semnificativă a comenzilor pe site.",
  "case.performance.author": "Angela Smith",
  "case.scoreLabel": "Scor viteză pagină",
  "case.visitsLabel": "Vizite trimestriale",
  "case.month.dec": "Dec",
  "case.month.jan": "Ian",
  "case.month.feb": "Feb",
  "case.month.mar": "Mar",
  "case.month.apr": "Apr",
  "case.month.may": "Mai",
  "pricing.eyebrow": "Prețuri",
  "pricing.title": "Prețuri clare",
  "pricing.titleMuted": " pentru echipe focusate.",
  "pricing.subtitle": "Scope-uri definite, costuri transparente și colaborări gândite în jurul nevoilor reale de business.",
  "pricing.plan.starter.name": "Starter",
  "pricing.plan.starter.price": "€1.200",
  "pricing.plan.starter.subtitle": "Pentru business-uri la început",
  "pricing.plan.starter.features.1": "Website sau landing page",
  "pricing.plan.starter.features.2": "Design UX/UI",
  "pricing.plan.starter.features.3": "Layout responsive",
  "pricing.plan.starter.features.4": "Setare SEO de bază",
  "pricing.plan.starter.cta": "Începe acum",
  "pricing.plan.pro.name": "Pro",
  "pricing.plan.pro.price": "€2.500",
  "pricing.plan.pro.subtitle": "Cea mai bună valoare pentru echipe în creștere",
  "pricing.plan.pro.features.1": "Totul din Starter",
  "pricing.plan.pro.features.2": "Integrări custom",
  "pricing.plan.pro.features.3": "Optimizare performanță",
  "pricing.plan.pro.features.4": "SEO & analytics avansat",
  "pricing.plan.pro.features.5": "Website-uri e-commerce (standard)",
  "pricing.plan.pro.features.6": "Dezvoltare aplicații mobile (apps simple: comenzi, programări, MVP)",
  "pricing.plan.pro.features.7": "Suport prioritar",
  "pricing.plan.pro.cta": "Pornește proiectul",
  "pricing.plan.enterprise.name": "Enterprise",
  "pricing.plan.enterprise.price": "Personalizat",
  "pricing.plan.enterprise.subtitle": "Construit pe nevoile business-ului tău",
  "pricing.plan.enterprise.features.1": "Platforme complexe & SaaS",
  "pricing.plan.enterprise.features.2": "Soluții e-commerce custom",
  "pricing.plan.enterprise.features.3": "Integrări ERP / API",
  "pricing.plan.enterprise.features.4": "Fluxuri de automatizare",
  "pricing.plan.enterprise.features.5": "Aplicații mobile avansate",
  "pricing.plan.enterprise.features.6": "Parteneriat pe termen lung",
  "pricing.plan.enterprise.cta": "Discută cu noi",
  "team.eyebrow": "Echipă",
  "team.titleA": "Oamenii din spatele",
  "team.titleB": "rezultatelor.",
  "team.subtitle": "O echipă restrânsă de designeri, ingineri și consultanți care construiesc produse digitale durabile.",
  "team.member.stefan.role": "Fondator & Lead Engineer",
  "team.member.stefan.desc": "Arhitectură de sistem, integrări complexe și dezvoltare hands-on pe multiple platforme.",
  "team.member.teodora.role": "Client & Growth Manager",
  "team.member.teodora.desc": "Relația cu clienții, coordonarea proiectelor și execuție orientată spre creștere.",
  "team.member.mihai.role": "Consultant Conținut & Strategie",
  "team.member.mihai.desc": "Producție de conținut, consultanță strategică și evaluare de risc în proiecte.",
  "team.member.dulca.role": "Consultant Principal Vânzări",
  "team.member.dulca.desc": "Outbound sales, atragere de clienți și negocieri la primul contact.",
  "faq.title": "Întrebări frecvente",
  "faq.subtitle": "Ai întrebări? Avem răspunsuri. Tot ce trebuie să știi despre colaborarea cu noi.",
  "faq.1.q": "Cât durează realizarea unui website?",
  "faq.1.a": "Durata depinde de complexitate și scop. Majoritatea proiectelor durează între 4–8 săptămâni. Stabilim un timeline clar încă din prima discuție.",
  "faq.2.q": "Faceți website-uri custom sau folosiți template-uri?",
  "faq.2.a": "Toate proiectele sunt realizate custom,m ai puțin dacă se dorește altceva precis. Nu folosim template-uri generice — fiecare soluție este construită în jurul obiectivelor tale.",
  "faq.3.q": "Ce include serviciul de SEO?",
  "faq.3.a": "SEO include optimizare tehnică, research de cuvinte cheie, îmbunătățiri on-page, optimizare de performanță și configurare analytics.",
  "faq.4.q": "Cum funcționează abonamentul lunar?",
  "faq.4.a": "Pentru servicii continue, oferim abonamente lunare pentru mentenanță, optimizări și suport de creștere. Planurile sunt flexibile și scalabile.",
  "faq.5.q": "Puteți face redesign la website-ul meu existent?",
  "faq.5.a": "Da. Refacem frecvent website-uri existente, îmbunătățind UX, performanța și claritatea vizuală, păstrând identitatea brandului.",
  "faq.6.q": "Cum încep?",
  "faq.6.a": "Scrie-ne prin formularul de contact sau prin Whatsapp la +40 747 754 180. Programăm un discovery call ca să înțelegem nevoile tale și să stabilim pașii următori.",
  "blog.section.titleA": "Tendințe noi",
  "blog.section.titleB": " și insight-uri de la echipa noastră.",
  "blog.section.subtitle": "Rămâi la curent cu proiectele noastre recente, trenduri și insight-uri din industrie.",
  "blog.section.cta": "Vezi tot",
  "contact.brand": "Nomadic Digital ®",
  "contact.form.title": "Ai un proiect în minte?",
  "contact.form.name": "Numele tău",
  "contact.form.email": "E-mail",
  "contact.form.message": "Spune-ne despre proiectul tău",
  "contact.form.sending": "Se trimite…",
  "contact.form.send": "Trimite mesaj",
  "contact.error.required": "Te rugăm să completezi toate câmpurile.",
  "contact.error.generic": "Nu am putut trimite mesajul.",
  "contact.success": "Mesaj trimis cu succes. Revenim către tine în scurt timp.",
  "contact.legal": "Prin trimitere, ești de acord cu Termenii & Politica de confidențialitate.",
  "contact.title": "Hai să vorbim.",
  "contact.subtitle": "Spune-ne despre proiectul tău — fie că e website, SEO sau marketing.",
  "contact.benefit1.title": "Răspuns rapid",
  "contact.benefit1.text": "Răspundem rapid și păstrăm comunicarea simplă și directă.",
  "contact.benefit2.title": "Pași clari",
  "contact.benefit2.text": "Vei primi un plan concret, un scope clar și un timeline.",
  "contact.card.role": "Client & Growth Manager",
  "contact.card.name": "Teodora Szelyes",
  "contact.card.cta": "Întreabă direct",
  "footer.desc": "Proiectăm și construim produse digitale performante — website-uri, platforme și sisteme de marketing care pot scala.",
  "footer.company": "Companie",
  "footer.company.about": "Despre",
  "footer.company.work": "Portofoliu",
  "footer.company.pricing": "Prețuri",
  "footer.company.contact": "Contact",
  "footer.services": "Servicii",
  "footer.services.1": "Web Design",
  "footer.services.2": "Dezvoltare Web",
  "footer.services.3": "SEO & Performanță",
  "footer.services.4": "Strategie de brand",
  "footer.follow": "Urmărește-ne",
  "footer.follow.instagram": "Instagram",
  "footer.follow.facebook": "Facebook",
  "footer.follow.linkedin": "LinkedIn",
  "footer.follow.x": "Twitter / X",
  "footer.copyright": "© {year} Nomadic Digital ® . Toate drepturile rezervate.",
  "footer.cta": "Începe un proiect",
  "footer.privacy": "Politica de confidențialitate",
  "footer.terms": "Termeni & condiții",
  "footer.logoAlt": "Logo Nomadic Digital",
  "about.pageTitle": "Despre noi",
  "about.studio": "Studio",
  "about.hero.bold": "Construim produse digitale cu claritate, disciplină și scop.",
  "about.hero.sub": "Fiecare decizie este intenționată — de la structură și performanță, până la felul în care se simte un brand atunci când cineva îl folosește.",
  "about.hero.socialProof": "De încredere pentru fondatori, operatori și echipe în creștere din toată lumea",
  "about.hero.note": "Fără zgomot. Fără straturi inutile. Doar muncă digitală bine făcută, care rezistă în timp.",
  "about.hero.imageAlt": "Colaborare în studio",
  "about.approach.kicker": "Fiecare proiect pe care îl acceptăm este gândit pentru succes pe termen lung.",
  "about.approach.line1": "Abordarea noastră este simplă:",
  "about.approach.line2": "funcționalitate, viteză și claritate,",
  "about.approach.line3": "fără complexitate inutilă.",
  "about.approach.body": "Nu promitem exagerat. Construim produse digitale durabile și bine gândite, care cresc odată cu nevoile reale ale unui business.",
  "about.approach.cta": "Portofoliu",
  "about.difference.title": "Ce ne diferențiază",
  "about.difference.subtitle": "Nu mai zgomotoși. Nu mai mari. Doar mai preciși acolo unde contează.",
  "about.difference.bold": "Nu vindem servicii.",
  "about.difference.rest": "Rezolvăm probleme de business specifice prin muncă digitală focusată și intenționată.",
  "about.difference.body": "Fără scope umflat. Fără straturi inutile. Fiecare linie de cod, fiecare alegere de design și fiecare integrare există cu un scop — să performeze, să scaleze și să reziste.",
  "about.difference.cta": "Contactează-ne",
  "about.editorial.1.title": "Cunoaște echipa",
  "about.editorial.2.title": "Cum lucrăm",
  "services.pageTitle": "Servicii",
  "services.capabilities": "Capabilități",
  "services.hero.bold": "Proiectăm și construim sisteme digitale care susțin creșterea reală.",
  "services.hero.sub": "De la strategie și UX până la dezvoltare complexă și integrări, munca noastră este orientată spre claritate, performanță și valoare pe termen lung.",
  "services.hero.note": "Nu oferim pachete generice. Fiecare colaborare este construită în jurul problemei de business, produsului și stadiului în care te afli.",
  "services.hero.right": "Ghidat de strategie. Orientat pe rezultate. Construit să reziste.",
  "services.hero.imageAlt": "Colaborare în studio",
  "services.01.kicker": "Platforme Web & E-commerce",
  "services.01.headline": "Platforme rapide și scalabile, construite pentru conversie.",
  "services.01.body": "Proiectăm și dezvoltăm website-uri moderne și platforme e-commerce care se încarcă rapid, scalează curat și susțin atât marketingul, cât și operațiunile.",
  "services.01.points.1": "Storefront-uri custom",
  "services.01.points.2": "Fluxuri B2C & B2B",
  "services.01.points.3": "Optimizare de performanță",
  "services.01.points.4": "Arhitectură pregătită pentru SEO",
  "services.02.kicker": "SaaS & Sisteme Custom",
  "services.02.headline": "Produse complexe, arhitectură curată.",
  "services.02.body": "Construim tool-uri interne, platforme SaaS și dashboard-uri custom unde fiabilitatea, securitatea și mentenanța contează.",
  "services.02.points.1": "Dashboard-uri de administrare",
  "services.02.points.2": "Sisteme cu roluri și permisiuni",
  "services.02.points.3": "Plăți & abonamente",
  "services.02.points.4": "Logică backend scalabilă",
  "services.02.points.5": "Integrări ERP",
  "services.02.points.6": "Integrări API complexe",
  "services.03.kicker": "UX, Brand & Product Design",
  "services.03.headline": "Design care elimină fricțiunea.",
  "services.03.body": "Proiectăm interfețe și sisteme de brand care sunt intenționate, clare și aliniate cu felul în care utilizatorii chiar se comportă.",
  "services.03.points.1": "Design UX & UI",
  "services.03.points.2": "Structură de produs",
  "services.03.points.3": "Sisteme de brand",
  "services.03.points.4": "Design systems",
  "services.03.points.5": "Print & producție on-demand",
  "services.03.points.6": "Materiale fizice de brand (cărți de vizită, apparel, packaging)",
  "services.04.kicker": "Marketing & Growth",
  "services.04.headline": "Marketing construit pe date, nu pe presupuneri.",
  "services.04.body": "Planificăm și executăm sisteme de marketing care susțin creșterea pe termen lung — aliniate cu produsul, infrastructura și constrângerile reale ale business-ului.",
  "services.04.points.1": "Marketing de performanță",
  "services.04.points.2": "SEO & strategie de conținut",
  "services.04.points.3": "Analytics & tracking de conversii",
  "services.04.points.4": "Structură de campanii & optimizare",
  "services.05.kicker": "Dezvoltare Aplicații Mobile",
  "services.05.headline": "Aplicații mobile construite pentru utilizare reală.",
  "services.05.body": "Proiectăm și dezvoltăm aplicații mobile fiabile, performante și ușor de menținut — focusate pe utilizabilitate pe termen lung, nu pe demo-uri de moment.",
  "services.05.points.1": "Aplicații iOS & Android",
  "services.05.points.2": "Dezvoltare cross-platform (Flutter / React Native)",
  "services.05.points.3": "Integrare API & backend",
  "services.05.points.4": "Optimizare de performanță & scalabilitate",
  "services.05.points.5": "Publicare în App Store & Play Store",
  "services.highlights.1.tag": "Engineering",
  "services.highlights.1.title": "Sisteme scalabile",
  "services.highlights.1.desc": "Arhitectură gândită să crească odată cu business-ul tău.",
  "services.highlights.2.tag": "UX / UI",
  "services.highlights.2.title": "Design de produs clar",
  "services.highlights.2.desc": "Interfețe care reduc fricțiunea și cresc conversia.",
  "services.bottomCta.title": "Ai o problemă specifică de rezolvat?",
  "services.bottomCta.sub": "Dacă nu ești sigur ce ți se potrivește, te ajutăm să alegi direcția corectă.",
  "services.bottomCta.button": "Începe o conversație",
  "contact.hero.imageAlt": "Imagine fundal",
  "contact.hero.eyebrow": "Începe o conversație",
  "contact.hero.title": "Hai să construim ceva",
  "contact.hero.titleMuted": "cu sens.",
  "contact.hero.subtitle": "Website-uri, e-commerce, aplicații mobile și strategii de creștere — construite cu claritate, performanță și valoare pe termen lung.",
  "contact.left.kicker": "Contact",
  "contact.left.title": "Hai să vorbim.",
  "contact.left.description": "Spune-ne despre proiectul tău. Revenim cu pași clari, fără obligații.",
  "contact.left.emailLabel": "Email",
  "contact.left.responseLabel": "Timp de răspuns",
  "contact.left.responseValue": "De obicei în maximum 48 de ore",
  "contact.form.nameLabel": "Nume",
  "contact.form.namePlaceholder": "Numele tău",
  "contact.form.emailLabel": "Email",
  "contact.form.emailPlaceholder": "tu@email.com",
  "contact.form.messageLabel": "Mesaj",
  "contact.form.messagePlaceholder": "Spune-ne pe scurt despre proiect",
  "contact.form.success": "Mesaj trimis cu succes. Revenim în scurt timp.",
  "contact.form.privacyNote": "Prin trimiterea formularului ești de acord cu Politica de confidențialitate.",
  "contact.form.genericError": "A apărut o eroare",
  portfolioPageTitle,
  portfolio,
  blog,
  privacy,
  terms,
  meta,
  about,
  contact,
  pricing,
  services,
  home
};
const DICTS = { en, ro };
const DEFAULT_LOCALE = "en";
const locale = writable(DEFAULT_LOCALE);
function getByPath(obj, path) {
  if (!obj || !path) return void 0;
  return path.split(".").reduce((acc, k) => acc != null ? acc[k] : void 0, obj);
}
function getValue(dict, key) {
  if (dict && Object.prototype.hasOwnProperty.call(dict, key)) return dict[key];
  return getByPath(dict, key);
}
const t = derived(locale, ($locale) => {
  const dict = DICTS[$locale] || DICTS[DEFAULT_LOCALE];
  const fallback = DICTS[DEFAULT_LOCALE];
  return (key, vars) => {
    let str = getValue(dict, key);
    if (str == null) str = getValue(fallback, key);
    if (typeof str !== "string") str = key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        str = str.replaceAll(`{${k}}`, String(v));
      }
    }
    return str;
  };
});
export {
  locale as l,
  t
};
